use_frameworks!
inhibit_all_warnings!

realm_version = '3.0.0'
# realm_version = '~> 3.0'
bg_realm_version = '1.0.0'
# bg_realm_version = '~> 1.0'

target 'iOS Example' do
  platform :ios, '9.0'
end

target 'BLResultsController_iOS' do
    platform :ios, '9.0'
    
    pod 'RealmSwift', realm_version
    pod 'BackgroundRealm', bg_realm_version
    
    target 'iOS Tests' do
        inherit! :search_paths
    end
end

target 'BLResultsController_watchOS' do
    platform :watchos, '3.0'
    
    pod 'RealmSwift', realm_version
    pod 'BackgroundRealm', bg_realm_version
end

target 'tvOS Example' do
    platform :tvos, '10.0'
end

target 'BLResultsController_tvOS' do
    platform :tvos, '10.0'
    
    pod 'RealmSwift', realm_version
    pod 'BackgroundRealm', bg_realm_version    

    target 'tvOS Tests' do
        inherit! :search_paths
    end
end

target 'macOS Example' do
    platform :osx, '10.10'
end

target 'BLResultsController_macOS' do
    platform :osx, '10.10'
    
    pod 'RealmSwift', realm_version
    pod 'BackgroundRealm', bg_realm_version
    
    target 'macOS Tests' do
        inherit! :search_paths
    end
end
